#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSctpM3UA", 1, "LocalInterface"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":[]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSctpM3UA", 0]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSctpM3UA", 0, "SectionM3UA"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSccp"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSccp", 0]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSccp", 0, "SlgPA"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSctpM3UA", 0, "SectionM3UA", "ServiceIndicator"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["IsColorLog"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, "TypeOfNumber"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, 0]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, "0"]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, 0.1]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, true]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=read_value

{"path":["SectionSmsc", 0, ???]}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSccp", 0, "TT"], "value": {"TT": 2}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSctpM3UA", 0, "SectionM3UA"], "value": {"TT": 2}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSctpM3UA", 0, "SectionM3UA, "Title"], "value": {"TT": UNKNOWN}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSctpM3UA", 0, "SectionM3UA", "Title"], "value": {"Title": "config - m3ua"}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSctpM3UA", 0, "SectionM3UA", "Title"], "value": {"Title": UNKNOWN}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{"path" : ["SectionSctpM3UA", 0, "SectionM3UA"], "value": {"Title": "config - m3ua"}}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "IsColorLog"
  ],
  "value": {
    "IsColorLog": "config - m3ua ==========="
  }
}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "IsColorLog"
  ],
  "value": {
    "IsColorLog": "config - m3ua ==========="
  }
}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "SectionSctpM3UA",
    0
  ],
  "value": {
    "Title": "config - m3ua---",
    "RemotePort": 1111000
  }
}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "SectionHttpApi",
    "Value"
  ],
  "value": {
    "Value": 9091
  }
}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "SectionHttpApi",
    "LocalPort"
  ],
  "value": {
    "LocalPort": 0x99
  }
}

#######

POST https://127.0.0.1:9091/horisen-mnp-scanner/conf?method=write_value&config=config_test_writing.yml

{
  "path": [
    "IsColorLog"
  ],
  "value": {
    "IsColorLog": null
  }
}
