"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from dal.group_ex import GroupEx


class GroupsTestDao:

    def __init__(self, ds):
        self.ds = ds

    def get_groups(self):
        """
        @rtype: list[GroupEx]
        """
        sql = """select g.*,  
                (select count(*) from tasks where g_id=g.g_id) as tasks_count 
                from groups g 
                order by g.g_id"""
        _res = []

        def _map_cb(row):
            _obj = GroupEx()
            _obj.g_id = row["g_id"]  # q <- q
            _obj.g_name = row["g_name"]  # q <- q
            _obj.g_comments = row["g_comments"]  # q <- q
            _obj.tasks_count = row["tasks_count"]  # q <- q
            _res.append(_obj)

        self.ds.query_all_rows(sql, [], _map_cb)
        return _res
