"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from django.db import models


class GroupLI(models.Model):
    g_id = models.AutoField(db_column='g_id', primary_key=True)
    g_name = models.TextField(db_column='g_name')
    g_tasks_count = models.TextField(db_column='g_tasks_count')

    class Meta:
        managed = False

    SQL = """select g.*,  
                (select count(*) from tasks where g_id=g.g_id) as g_tasks_count 
                from groups g 
                order by g.g_id"""
