"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from django.db import models


class Project(models.Model):
    p_id = models.AutoField(db_column='p_id', primary_key=True)
    p_name = models.CharField(db_column='p_name', max_length=256)

    class Meta:
        managed = False
        db_table = 'projects'
