"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""

from django.db import models


class ProjectLi(models.Model):
    p_id = models.AutoField(db_column='p_id', primary_key=True)
    p_name = models.TextField(db_column='p_name')
    p_tasks_count = models.TextField(db_column='p_tasks_count')

    class Meta:
        managed = False

    SQL = """select p.*, 
                (select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
                from projects p 
                order by p.p_id"""
