"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from dal.task import Task


class TasksDao:

    def __init__(self, ds):
        self.ds = ds

    def create_task(self, p):
        """
        (C)RUD: tasks
        Generated values are passed to DTO.
        @type p: Task
        @rtype: None
        @raise: Exception if no rows inserted.
        """
        self.ds.create_one(p)

    def read_task(self, t_id):
        """
        C(R)UD: tasks
        @type t_id: int
        @rtype: Task
        @raise: Exception if amount of returned rows != 1.
        """
        return self.ds.read_one(Task, {'t_id': t_id})

    def delete_task(self, t_id):
        """
        CRU(D): tasks
        @type t_id: int
        @rtype: int (the number of affected rows)
        """
        return self.ds.delete_one(Task, {'t_id': t_id})
