"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from django.db import models


class Task(models.Model):
    t_id = models.AutoField(db_column='t_id', primary_key=True)
    g_id = models.IntegerField(db_column='g_id')
    t_priority = models.IntegerField(db_column='t_priority')
    t_date = models.CharField(db_column='t_date', max_length=65535)
    t_subject = models.CharField(db_column='t_subject', max_length=65535)
    t_comments = models.CharField(db_column='t_comments', max_length=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tasks'
